language: rust
os: linux
dist: trusty
cache: cargo
rust:
- stable
- beta
- nightly
jobs:
  allow_failures:
  - rust: nightly
before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
  fi
script:
- cargo clean
- cargo build --verbose --all
- cargo test --lib --verbose -- --test-threads 1
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --out Xml --ignore-tests -- --test-threads 1
    bash <(curl -s https://codecov.io/bash)
  fi
deploy:
  provider: cargo
  token:
    secure: S1cIXHqYuRzDxB3Y0QuMbVlxC8uKncXC8aS2bgyWICNnN4bLWqyrHdBhzMBiZqpvYtR9p5X3+WehSgmDCPiQB25UeH8fswf3foMkNp2paHBvEftAH7+/LWZL5N7O8Fh56z1ADQ8NcEd3ACrLgNpX/nSZ7nPGNAVqnCmyjNp2pfDeWYqCIoCYf7OLIlE7SVwzaFkUSCoYz43Re9occfF9gHymWq8vY6wbuWgP2mYVSy5DV/CC0jBekY5atUgUq9ggYOafne564uWmDbr7n6NOhILFinp27dIrQwPxLQq0F9gdPbkPCyF7tMLx8oTvF4K3i58Up6GDoDdqDpBcpP8C5C51/qycPFmTjat3ZiLPBqfd+2kY6F7TuZfdKvf8twBif8ZarXVTEPeeuMEX93NAvS+Dsm704/Ewu1eN8W+DwAJsNS/nM8exkGm9pZezYZn3sjGeB0AXXjEqS0ivfNcXSEjv1GbQPYDUYsAK4SjTK6NDbAdYXiFPV+yQhsDT45HVW62QI4x4kFBabkxhy/b8JwIXRlE72LVv+/XUSDKNbknXax+rXpkV44UFgrJ6ZhPrPS7/gTn0txQ4NvIlu4Z9whH/gdDs3v0zu9ADGGmkRBFMd2kxg+lBNuQs3caEs2U0KcbTKubRwWzgYjyioll3o45fFnxdFdukDG/pf2GiZLE=
  on:
    tags: true
